### ISSUE TITLE
Request for feedback

### ISSUE THREAD

**Issue by jeskew** [aws/aws-js-sns-message-validator#1]
/cc @chrisradek

**Comment by zanemcca** [comment]
This is great. Is it going to be merged into aws-sdk? If not are you planning on posting it to the npm repository?

**Comment by jeskew** [comment]
Hi @zanemcca,

The current plan is to keep this separate. We just published it as an [npm module](https://www.npmjs.com/package/sns-validator).

**Comment by jeskew** [comment]
Thanks for the feedback!
