### ISSUE TITLE
Support Proxy (Agent)

### ISSUE THREAD

**Issue by kroney** [aws/aws-js-sns-message-validator#21]
Seems like the module does not support any proxy options.
Would be great to have them similarly to the aws-sdk httpOptions (https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html).
Thanks

**Comment by andrejewski** [comment]
I would also greatly appreciate `httpOptions` support. Without this, we'll have to fork and hand-roll our own extensions and that's troublesome.
